import { createPiece, PieceAuth, Property } from '@activepieces/pieces-framework';
import { PieceCategory } from '@activepieces/shared';
import { createCustomApiCallAction } from '@activepieces/pieces-common';

// Security actions
import {
  security_ping,
  security_change_racf_password,
  security_validate_racf_user,
} from './lib/actions/security';

// Bank Control actions
import {
  bank_control_get_branch_detail,
  bank_control_get_branch_info,
  bank_control_get_processing_date,
  bank_control_get_holiday_calendar,
  bank_control_get_gl_account,
  bank_control_get_institution_info,
  bank_control_get_officer,
  bank_control_get_product_codes,
  bank_control_get_transaction_codes,
  bank_control_get_routing_number,
} from './lib/actions/bank-control';

// Customer actions
import {
  customer_get,
  customer_delete,
  customer_create_individual,
  customer_create_organization,
  customer_get_combined,
  customer_update_combined,
  customer_accounts_address_edit,
  customer_accounts_delete,
  customer_accounts_get_name_address,
  customer_accounts_update_name_address,
  customer_accounts_create,
  customer_accounts_update_related_address,
  customer_address_edit,
  customer_update_addresses,
  customer_get_aliases,
  customer_create_alias,
  customer_update_alias,
  customer_delete_alias,
  customer_get_due_diligence,
  customer_update_due_diligence,
  customer_get_email_addresses,
  customer_create_email_address,
  customer_delete_email_address,
  customer_get_phone_numbers,
  customer_create_phone_number,
  customer_update_phone_number,
  customer_delete_phone_number,
  customer_search_by_name,
  customer_search_by_customer_number,
  customer_search_by_tax_number,
  customer_search_by_phone,
  customer_search_by_cip_id,
  customer_get_statements,
  customer_create_combined_statement,
  customer_update_combined_statement,
  customer_delete_combined_statement,
  customer_get_remarks,
  customer_create_remark,
  customer_update_remark,
  customer_delete_remark,
  customer_get_relationships,
  customer_create_relationship,
  customer_update_relationship,
  customer_delete_relationship,
  customer_get_profile,
  customer_update_profile,
} from './lib/actions/customer';

// Deposit actions
import {
  deposit_get_account,
  deposit_create_account,
  deposit_update_account,
  deposit_close_account,
  deposit_get_balance,
  deposit_get_interest_rates,
  deposit_update_interest_rates,
  deposit_get_transactions,
  deposit_post_transaction,
  deposit_reverse_transaction,
  deposit_transfer,
  deposit_get_holds,
  deposit_create_hold,
  deposit_update_hold,
  deposit_release_hold,
  deposit_get_escrow_accounts,
  deposit_create_escrow_account,
  deposit_update_escrow_account,
  deposit_calculate,
  deposit_originate,
  deposit_update_maintenance,
} from './lib/actions/deposit';

// Loan actions
import {
  loan_get_account,
  loan_create_account,
  loan_update_account,
  loan_get_notes,
  loan_create_note,
  loan_get_note_balances,
  loan_renew_note,
  loan_increase_note,
  loan_get_payment_info,
  loan_post_payment,
  loan_reverse_payment,
  loan_get_collateral,
  loan_create_collateral,
  loan_update_collateral,
  loan_delete_collateral,
  loan_get_fees,
  loan_create_fee,
  loan_get_payoff_quote,
  loan_payoff,
  loan_change_rate_immediate,
  loan_get_pending_rate_changes,
  loan_get_transactions,
  loan_disburse,
  loan_board,
} from './lib/actions/loan';

export const fisIbsAuth = PieceAuth.CustomAuth({
  description: 'FIS IBS API credentials',
  required: true,
  props: {
    baseUrl: Property.ShortText({
      displayName: 'Base URL',
      description: 'The base URL for the FIS IBS API (e.g., https://api-gw-uat.fisglobal.com/rest)',
      required: true,
      defaultValue: 'https://api-gw-uat.fisglobal.com/rest',
    }),
    organizationId: Property.ShortText({
      displayName: 'Organization ID',
      description: 'Your FIS Organization ID',
      required: true,
    }),
    sourceId: Property.ShortText({
      displayName: 'Source ID',
      description: 'Source ID provided by FIS (e.g., APIGWY)',
      required: true,
      defaultValue: 'APIGWY',
    }),
    applicationId: Property.ShortText({
      displayName: 'Application ID',
      description: 'Application ID for your integration',
      required: true,
    }),
    ibsAuthorization: PieceAuth.SecretText({
      displayName: 'IBS Authorization',
      description: 'Authorization token for IBS APIs',
      required: true,
    }),
    securityTokenType: Property.StaticDropdown({
      displayName: 'Security Token Type',
      description: 'Type of security token being used',
      required: false,
      options: {
        options: [
          { label: 'JWT', value: 'JWT' },
          { label: 'SAML', value: 'SAML' },
          { label: 'OAuth', value: 'OAuth' },
        ],
      },
      defaultValue: 'JWT',
    }),
  },
});

export const fisIbs = createPiece({
  displayName: 'FIS IBS',
  auth: fisIbsAuth,
  minimumSupportedRelease: '0.20.0',
  logoUrl: 'https://s6.imgcdn.dev/Y1izHg.jpg',
  authors: ['vqnguyen1'],
  categories: [PieceCategory.BUSINESS_INTELLIGENCE],
  actions: [
    // Security & Authentication (3)
    security_ping,
    security_change_racf_password,
    security_validate_racf_user,

    // Bank Control (10)
    bank_control_get_branch_detail,
    bank_control_get_branch_info,
    bank_control_get_processing_date,
    bank_control_get_holiday_calendar,
    bank_control_get_gl_account,
    bank_control_get_institution_info,
    bank_control_get_officer,
    bank_control_get_product_codes,
    bank_control_get_transaction_codes,
    bank_control_get_routing_number,

    // Customer actions (46)
    customer_get,
    customer_delete,
    customer_create_individual,
    customer_create_organization,
    customer_get_combined,
    customer_update_combined,
    customer_accounts_address_edit,
    customer_accounts_delete,
    customer_accounts_get_name_address,
    customer_accounts_update_name_address,
    customer_accounts_create,
    customer_accounts_update_related_address,
    customer_address_edit,
    customer_update_addresses,
    customer_get_aliases,
    customer_create_alias,
    customer_update_alias,
    customer_delete_alias,
    customer_get_due_diligence,
    customer_update_due_diligence,
    customer_get_email_addresses,
    customer_create_email_address,
    customer_delete_email_address,
    customer_get_phone_numbers,
    customer_create_phone_number,
    customer_update_phone_number,
    customer_delete_phone_number,
    customer_search_by_name,
    customer_search_by_customer_number,
    customer_search_by_tax_number,
    customer_search_by_phone,
    customer_search_by_cip_id,
    customer_get_statements,
    customer_create_combined_statement,
    customer_update_combined_statement,
    customer_delete_combined_statement,
    customer_get_remarks,
    customer_create_remark,
    customer_update_remark,
    customer_delete_remark,
    customer_get_relationships,
    customer_create_relationship,
    customer_update_relationship,
    customer_delete_relationship,
    customer_get_profile,
    customer_update_profile,

    // Deposit actions (21)
    deposit_get_account,
    deposit_create_account,
    deposit_update_account,
    deposit_close_account,
    deposit_get_balance,
    deposit_get_interest_rates,
    deposit_update_interest_rates,
    deposit_get_transactions,
    deposit_post_transaction,
    deposit_reverse_transaction,
    deposit_transfer,
    deposit_get_holds,
    deposit_create_hold,
    deposit_update_hold,
    deposit_release_hold,
    deposit_get_escrow_accounts,
    deposit_create_escrow_account,
    deposit_update_escrow_account,
    deposit_calculate,
    deposit_originate,
    deposit_update_maintenance,

    // Loan actions (24)
    loan_get_account,
    loan_create_account,
    loan_update_account,
    loan_get_notes,
    loan_create_note,
    loan_get_note_balances,
    loan_renew_note,
    loan_increase_note,
    loan_get_payment_info,
    loan_post_payment,
    loan_reverse_payment,
    loan_get_collateral,
    loan_create_collateral,
    loan_update_collateral,
    loan_delete_collateral,
    loan_get_fees,
    loan_create_fee,
    loan_get_payoff_quote,
    loan_payoff,
    loan_change_rate_immediate,
    loan_get_pending_rate_changes,
    loan_get_transactions,
    loan_disburse,
    loan_board,

    // Custom API call for any other endpoints
    createCustomApiCallAction({
      baseUrl: (auth) => (auth as any).baseUrl || 'https://api-gw-uat.fisglobal.com/rest',
      auth: fisIbsAuth,
      authMapping: async (auth) => {
        const authObj = auth as any;
        const uuid = crypto.randomUUID();
        const headers: Record<string, string> = {
          'organization-id': authObj.organizationId,
          'source-id': authObj.sourceId,
          'application-id': authObj.applicationId,
          'uuid': uuid,
          'ibs-authorization': authObj.ibsAuthorization,
        };
        if (authObj.securityTokenType) {
          headers['security-token-type'] = authObj.securityTokenType;
        }
        return headers;
      },
    }),
  ],
  triggers: [],
});
