"""Generates one Activepieces action per SellerCloud REST operation.

Run from the piece root:
    python3 tools/generate-actions.py ../../../../.claude/todo/sellercloud-rest-openapi/sellercloud_rest_v1.json

Everything under src/lib/actions/generated is overwritten; hand-written actions
live in src/lib/actions and are never touched.
"""
import json
import os
import re
import sys
from collections import Counter, defaultdict

OUT_DIR = 'src/lib/actions/generated'
# The piece's own auth handles /api/token, and these add nothing to a flow.
SKIP_OPERATIONS = {'Authentication_CreateLocalToken', 'Diagnostics_Get'}
SCALARS = ('string', 'integer', 'number', 'boolean')


def main():
    spec = json.load(open(sys.argv[1]))
    definitions = spec['definitions']
    by_tag = defaultdict(list)
    for path, methods in spec['paths'].items():
        for method, op in methods.items():
            if not isinstance(op, dict) or 'operationId' not in op:
                continue
            if op['operationId'] in SKIP_OPERATIONS:
                continue
            by_tag[(op.get('tags') or ['Misc'])[0]].append((path, method.upper(), op))

    os.makedirs(OUT_DIR, exist_ok=True)
    for stale in os.listdir(OUT_DIR):
        os.remove(os.path.join(OUT_DIR, stale))

    action_names = assign_action_names(by_tag)

    modules = []
    total = 0
    for tag in sorted(by_tag):
        ops = sorted(by_tag[tag], key=lambda o: o[2]['operationId'])
        module = kebab(tag)
        export = camel(tag) + 'Actions'
        open(f'{OUT_DIR}/{module}.ts', 'w').write(render_module(tag, export, ops, definitions, action_names))
        modules.append((module, export))
        total += len(ops)

    barrel = ['// Generated by tools/generate-actions.py. Do not edit.', '']
    barrel += [f"import {{ {export} }} from './{module}';" for module, export in modules]
    barrel += ['', 'export const generatedActions = [']
    barrel += [f'    ...{export},' for _, export in modules]
    barrel += ['];', '']
    open(f'{OUT_DIR}/index.ts', 'w').write('\n'.join(barrel))
    print(f'{total} actions across {len(modules)} modules')


def assign_action_names(by_tag):
    operations = [(path, method, op) for ops in by_tag.values() for path, method, op in ops]
    duplicates = {
        operation_id
        for operation_id, count in Counter(op['operationId'] for *_, op in operations).items()
        if count > 1
    }
    names, taken = {}, set()
    for path, method, op in sorted(operations):
        name = snake(op['operationId'])
        if op['operationId'] in duplicates:
            path_params = re.findall(r'\{(\w+)\}', path)
            name += '_by_' + '_'.join(snake(p) for p in path_params) if path_params else '_' + method.lower()
        candidate, index = name, 2
        while candidate in taken:
            candidate, index = f'{name}_{index}', index + 1
        taken.add(candidate)
        names[(path, method)] = candidate
    return names


def render_module(tag, export, ops, definitions, action_names):
    bodies = [render_action(tag, path, method, op, definitions, action_names) for path, method, op in ops]
    header = [
        '// Generated by tools/generate-actions.py. Do not edit.',
        "import { HttpMethod } from '@activepieces/pieces-common';",
        "import { createAction, Property } from '@activepieces/pieces-framework';",
        "import { sellercloudAuth } from '../../auth';",
        "import { sellercloudClient } from '../../common/client';",
        "import { generatedActionUtils } from '../../common/generated-action-utils';",
        '',
    ]
    names = [action_names[(path, method)] for path, method, _ in ops]
    footer = [f'export const {export} = [', *[f'    {camel(n)},' for n in names], '];', '']
    return '\n'.join(header + bodies + footer)


def render_action(tag, path, method, op, definitions, action_names):
    name = action_names[(path, method)]
    params = op.get('parameters', [])
    path_params = [p for p in params if p['in'] == 'path']
    query_params = [p for p in params if p['in'] == 'query']
    body_param = next((p for p in params if p['in'] == 'body'), None)

    props, query_map, body_fields = [], [], []
    for param in path_params + query_params:
        key = sanitize(param['name'])
        props.append(f'        {key}: {render_prop(param, param)},')
        if param['in'] == 'query':
            query_map.append((key, param['name'], param.get('type')))

    body_mode = 'none'
    if body_param is not None:
        schema = resolve(body_param.get('schema', {}), definitions)
        fields = schema.get('properties') or {}
        if fields and all(f.get('type') in SCALARS and '$ref' not in f for f in fields.values()):
            body_mode = 'fields'
            required = set(schema.get('required') or [])
            for field, field_schema in fields.items():
                key = body_key(field, props)
                props.append(f'        {key}: {render_prop(dict(field_schema, name=field, required=field in required), field_schema)},')
                body_fields.append((key, field))
        else:
            body_mode = 'json'
            skeleton = json.dumps(skeleton_of(body_param.get('schema', {}), definitions), indent=4)
            props.append(f'        body: {render_json_prop(body_param, skeleton)},')

    lines = [f'const {camel(name)} = createAction({{']
    lines.append('    auth: sellercloudAuth,')
    lines.append(f"    name: '{name}',")
    lines.append(f"    displayName: '{escape(display_name(tag, op))}',")
    lines.append(f"    description: '{escape(description(method, path, op))}',")
    lines.append('    props: {' if props else '    props: {},')
    lines.extend(props)
    if props:
        lines.append('    },')
    lines.append('    async run(context) {')
    lines.append(f'        const {{ path, queryParams, body }} = generatedActionUtils.buildRequest({{')
    lines.append(f"            pathTemplate: '{path}',")
    lines.append(f'            pathParams: [{", ".join(repr_ts(sanitize(p["name"])) for p in path_params)}],')
    lines.append(f'            queryParams: [{", ".join("{ key: " + repr_ts(k) + ", name: " + repr_ts(n) + ", isArray: " + ("true" if t == "array" else "false") + " }" for k, n, t in query_map)}],')
    lines.append(f'            bodyFields: [{", ".join("{ key: " + repr_ts(k) + ", name: " + repr_ts(n) + " }" for k, n in body_fields)}],')
    lines.append(f"            bodyMode: '{body_mode}',")
    lines.append('            propsValue: context.propsValue,')
    lines.append('        });')
    lines.append('        return sellercloudClient.request({')
    lines.append('            auth: context.auth.props,')
    lines.append(f'            method: HttpMethod.{method},')
    lines.append('            path,')
    lines.append('            queryParams,')
    lines.append('            body,')
    lines.append('        });')
    lines.append('    },')
    lines.append('});')
    lines.append('')
    return '\n'.join(lines)


def render_prop(param, schema):
    display = humanize(param.get('name', 'value'))
    required = 'true' if param.get('required') else 'false'
    parts = [f"            displayName: '{escape(display)}',"]
    if param.get('description'):
        parts.append(f"            description: '{escape(one_line(param['description']))}',")
    parts.append(f'            required: {required},')
    kind = 'ShortText'
    if schema.get('enum'):
        kind = 'StaticDropdown'
        legend = enum_legend(param.get('description') or '')
        options = ',\n'.join(
            f"                    {{ label: '{escape(legend.get(str(v), str(v)))}', value: {json.dumps(v)} }}"
            for v in schema['enum']
        )
        parts.append('            options: {\n                options: [\n' + options + ',\n                ],\n            },')
    elif schema.get('type') == 'array':
        kind = 'Array'
    elif schema.get('type') in ('integer', 'number'):
        kind = 'Number'
    elif schema.get('type') == 'boolean':
        kind = 'Checkbox'
    elif schema.get('format') == 'date-time':
        kind = 'DateTime'
    return f'Property.{kind}({{\n' + '\n'.join(parts) + '\n        })'


# SellerCloud documents its numeric enums inline, e.g. "0 = Normal , 1 = FBA".
def enum_legend(description):
    pairs = re.findall(r'(-?\d+)\s*=\s*([A-Za-z0-9_][A-Za-z0-9_ /+.-]*)', description)
    return {value: humanize(label.strip().rstrip(',').strip()) for value, label in pairs}


def render_json_prop(param, skeleton):
    description = one_line(param.get('description') or 'Request body.')
    return (
        'Property.Json({\n'
        "            displayName: 'Body',\n"
        f"            description: '{escape(description)}',\n"
        f'            required: {"true" if param.get("required") else "false"},\n'
        f'            defaultValue: {indent_json(skeleton)},\n'
        '        })'
    )


def skeleton_of(schema, definitions, seen=None, depth=0):
    seen = seen or set()
    ref = schema.get('$ref')
    if ref:
        if ref in seen or depth > 4:
            return {}
        seen = seen | {ref}
        return skeleton_of(definitions.get(ref.split('/')[-1], {}), definitions, seen, depth + 1)
    if schema.get('type') == 'array':
        return [skeleton_of(schema.get('items', {}), definitions, seen, depth + 1)]
    fields = schema.get('properties')
    if fields:
        return {name: skeleton_of(field, definitions, seen, depth + 1) for name, field in fields.items()}
    if schema.get('enum'):
        return schema['enum'][0]
    return {'string': '', 'integer': 0, 'number': 0, 'boolean': False}.get(schema.get('type'), None)


def resolve(schema, definitions, depth=0):
    ref = schema.get('$ref')
    if ref and depth < 5:
        return resolve(definitions.get(ref.split('/')[-1], {}), definitions, depth + 1)
    return schema


def display_name(tag, op):
    summary = one_line(op.get('summary') or '')
    label = summary.rstrip('.') if summary else humanize(op['operationId'].split('_', 1)[-1])
    if len(label) > 60:
        label = humanize(op['operationId'].split('_', 1)[-1])
    return f'{tag}: {label}'


def description(method, path, op):
    summary = one_line(op.get('summary') or '').rstrip('.')
    prefix = f'{summary}. ' if summary else ''
    return f'{prefix}{method} {path}'


def body_key(field, existing):
    key = sanitize(field)
    if any(line.strip().startswith(f'{key}:') for line in existing):
        return f'{key}_body'
    return key


def sanitize(name):
    cleaned = re.sub(r'^model\.', '', name)
    cleaned = re.sub(r'[^A-Za-z0-9]+', '_', cleaned).strip('_')
    return cleaned[0].lower() + cleaned[1:] if cleaned else 'value'


def humanize(name):
    cleaned = re.sub(r'^model\.', '', name)
    cleaned = re.sub(r'[_.]+', ' ', cleaned)
    cleaned = re.sub(r'(?<=[a-z0-9])(?=[A-Z])', ' ', cleaned)
    return ' '.join(word[:1].upper() + word[1:] for word in cleaned.split())


def snake(name):
    cleaned = re.sub(r'[^A-Za-z0-9]+', '_', name)
    cleaned = re.sub(r'(?<=[a-z0-9])(?=[A-Z])', '_', cleaned)
    return re.sub(r'_+', '_', cleaned).strip('_').lower()


def camel(name):
    head, *rest = snake(name).split('_')
    return head + ''.join(word[:1].upper() + word[1:] for word in rest)


def kebab(name):
    return snake(name).replace('_', '-')


def one_line(text):
    return re.sub(r'\s+', ' ', text).strip()


def escape(text):
    return text.replace('\\', '\\\\').replace("'", "\\'")


def indent_json(text):
    return text.replace('\n', '\n            ')


def repr_ts(value):
    return json.dumps(value)


if __name__ == '__main__':
    main()
